name: Build

on: push

jobs:
  build:
    name: Build our App
    runs-on: ubuntu-latest
    steps:
      - name: Pull respository
        uses: actions/checkout@v2
      - name: Run Current Directory
        run: pwd
      - name: List Files in Directory
        run: ls
      - name: Check dotnet build
        working-directory: ./MotionAPI
        run: dotnet build
      - name: run what contains in folder
        run: ls MotionAPI -R
      - name: check npm cli version
        run: npm -v